[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Packages.php-cs-fixer"]

[phases.build]
cmds = [
  "composer install --no-dev --prefer-dist",
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan migrate --force"
]

[phases.start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"
